### ISSUE TITLE
map-matching error 

### ISSUE THREAD

**Issue by merriaux** [graphhopper/map-matching#100]
Hi,
I am trying to map-match gps data from high accuracy GPS RTK, and I obtain the following error :
        No edge matches found for path. Too short? Sequence size 1288
        java.lang.IllegalStateException: No edge matches found for path. Too short? Sequence size 1288
	at com.graphhopper.matching.MapMatching.computeMatchedEdges(MapMatching.java:367)
	at com.graphhopper.matching.MapMatching.computeMatchResult(MapMatching.java:327)
	at com.graphhopper.matching.MapMatching.doWork(MapMatching.java:189)
	at com.graphhopper.matching.MapMatchingMain.start(MapMatchingMain.java:111)
	at com.graphhopper.matching.MapMatchingMain.main(MapMatchingMain.java:44)
I have tried with 1m and 10m subsampled gps file with the same result.
If you want to try, I have uploaded the file on drive :
- 10m subsampled gps file : https://drive.google.com/open?id=0ByM3q2Q6aEv0TVpjY3h5blUtLUU
- 1m subsampled gps file : https://drive.google.com/open?id=0ByM3q2Q6aEv0eno4VjE1dENnT00

You will need the map upper-normandy :  http://download.geofabrik.de/europe/france/haute-normandie.html

Many thank for future help.
regards
Pierre

**Comment by karussell** [comment]
Please use our forum to ask usage questions and if this turns out to be a bug then you post here.
