### ISSUE TITLE
Run 0.9 Version

### ISSUE THREAD

**Issue by kshmr** [graphhopper/map-matching#108]
I've tried to run UI mode with command `./map-matching.sh action=start-server` , but I got error :

```sh
using java
2017-11-15 17:46:54,345 [main] INFO  com.graphhopper.http.CmdArgsModule - jsonp disabled
Exception in thread "main" java.lang.IllegalStateException: Cannot load properties to fetch EncodingManager configuration at: ./graph-cache/
	at com.graphhopper.routing.util.EncodingManager.create(EncodingManager.java:155)
	at com.graphhopper.GraphHopper.load(GraphHopper.java:725)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:617)
	at com.graphhopper.http.GraphHopperModule$3.start(GraphHopperModule.java:182)
	at com.graphhopper.http.GHServer.start(GHServer.java:118)
	at com.graphhopper.http.GHServer.start(GHServer.java:62)
	at com.graphhopper.matching.http.MatchServer.main(MatchServer.java:36)

```

I used version `0.9`, maven version `3.3.9` and java `openjdk version "1.8.0_151"`. Did I miss something during instalation ?

**Comment by karussell** [comment]
Please follow the instructions like that an import is necessary before and questions should go first to our forum, then if this turns out to be a bug they'll be reported as issue
