### ISSUE TITLE
IllegalStateException: Cannot fetch null EdgeState

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#127]
```
java.lang.IllegalStateException: Cannot fetch null EdgeState
        at com.graphhopper.matching.EdgeMatch.<init>(EdgeMatch.java:36)
        at com.graphhopper.matching.MapMatching.computeMatchResult(MapMatching.java:559)
        at com.graphhopper.matching.MapMatching.doWork(MapMatching.java:220)
        at com.graphhopper.matching.http.MapMatchingResource.match(MapMatchingResource.java:110)
        at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by karussell** [comment]
It can be triggered with two identical points:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns="http://www.topografix.com/GPX/1/0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd" xmlns:xsi="http://www.w3.org">
<trk>
<trkseg>
<trkpt lat="51.074086" lon="13.737159">
<ele>0</ele></trkpt>
<trkpt lat="51.074086" lon="13.737159">
<ele>0</ele></trkpt>
</trkseg></trk></gpx>
```

**Comment by michaz** [comment]
Thanks! Here we go.
