### ISSUE TITLE
map matching NPE

### ISSUE THREAD

**Issue by karussell** [graphhopper/map-matching#154]
Probably there is just a "non null" annotation missing for `trkseg`?

    ```
    java.lang.NullPointerException: null
            at com.graphhopper.matching.gpx.Trk.getEntries(Trk.java:39)
            at com.graphhopper.matching.http.MapMatchingResource.match(MapMatchingResource.java:108)
            at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
    ```

**Comment by michaz** [comment]
Argh. I think I do have to initialize with a default here.
