### ISSUE TITLE
Encoder for car not found. Existing: foot|

### ISSUE THREAD

**Issue by michalwoz** [graphhopper/map-matching#160]
I have problem with version 1.0:
java -jar matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar import **--vehicle=foot** xxx.pbf

than I cannot do any:
java -jar matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar match yyy.gpx

got an error:
`loading graph from cache
java.lang.IllegalArgumentException: Encoder for car not found. Existing: foot|speed_factor=1.0|speed_bits=4|turn_costs=false|version=5
        at com.graphhopper.routing.util.EncodingManager.getEncoder(EncodingManager.java:394)
        at com.graphhopper.routing.util.EncodingManager.getEncoder(EncodingManager.java:385)
        at com.graphhopper.matching.MapMatching.<init>(MapMatching.java:104)
        at com.graphhopper.matching.cli.MatchCommand.run(MatchCommand.java:83)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.matching.http.MapMatchingApplication.main(MapMatchingApplication.java:16)`

version 0.13 works perfetcly

**Comment by braito4** [comment]
I've same error here even on 1.0-Pre4

Works on .1.0-pre2

**Comment by karussell** [comment]
Did you recreate the graph?

> --vehicle=foot 

This won't work anymore. You should put this in the config file instead.

Please use our public for future questions: https://discuss.graphhopper.com/c/graphhopper/map-matching

**Comment by karussell** [comment]
This is indeed a bug. Thanks for raising the issue. Will fix.

**Comment by braito4** [comment]
bug solved

**Comment by braito4** [comment]
127.0.0.1 - - [10/Dec/2019:12:53:16 +0000] "GET /favicon.ico HTTP/1.1" 404 43 "http://localhost:8989/app/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" 27
INFO  [2019-12-10 12:53:37,579] com.graphhopper.http.IllegalArgumentExceptionMapper: bad request: Encoder for car not found. Existing: foot|speed_factor=1.0|speed_bits=4|turn_costs=false|version=5

**Comment by SimonCoulombe** [comment]
Hey everyone,
I get the same error using today's master  version.    (trying to figure out how to check version)
```

base) simon@ryzen:~/git/map-matching$ java -jar matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar match  pouet.gpx
loading graph from cache
java.lang.IllegalArgumentException: Encoder for car not found. Existing: bike|speed_factor=2.0|speed_bits=4|turn_costs=false|version=2
        at com.graphhopper.routing.util.EncodingManager.getEncoder(EncodingManager.java:394)
        at com.graphhopper.routing.util.EncodingManager.getEncoder(EncodingManager.java:385)
        at com.graphhopper.matching.MapMatching.<init>(MapMatching.java:104)
        at com.graphhopper.matching.cli.MatchCommand.run(MatchCommand.java:83)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.graphhopper.matching.http.MapMatchingApplication.main(MapMatchingApplication.java:16)

```
