### ISSUE TITLE
Error saving matching large gpx.

### ISSUE THREAD

**Issue by braito4** [graphhopper/map-matching#164]
I've got this error saving a matching of a large gpx. 
I'm using the latest core (Use GH core 1.0-pre12)

java -jar -Xmx10g matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar match cf.gpx --gps_accuracy 5 --max_visited_nodes 100000
loading graph from cache
cf.gpx
	matches:	5987, gps entries:17348
	gpx length:	760336.06 vs 760439.7
	export results to:/xxxx/cf.gpx.res.gpx
Problem with file cf.gpx
java.lang.ArrayIndexOutOfBoundsException: Index 76 out of bounds for length 76
	at com.graphhopper.storage.RAMIntDataAccess.getInt(RAMIntDataAccess.java:208)
	at com.graphhopper.storage.GHNodeAccess.getLatitude(GHNodeAccess.java:69)
	at com.graphhopper.routing.InstructionsFromEdges.next(InstructionsFromEdges.java:147)
	at com.graphhopper.routing.Path.forEveryEdge(Path.java:207)
	at com.graphhopper.routing.InstructionsFromEdges.calcInstructions(InstructionsFromEdges.java:130)
	at com.graphhopper.util.PathMerger.doWork(PathMerger.java:115)
	at com.graphhopper.matching.cli.MatchCommand.run(MatchCommand.java:113)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.graphhopper.matching.http.MapMatchingApplication.main(MapMatchingApplication.java:16)
gps import took:0.22843875s, match took: 4.295936

**Comment by karussell** [comment]
This does not look good, still we won't be able to fix it with the information you provided. Please include the osm.pbf you used (the smaller the better), the config.yml and also the smallest gpx that fails.

**Comment by braito4** [comment]
smalls gpx didn't fail only the big ones (760km in this case)
it worked well in 1.0-pre10 (i usually try the same files after update graphhopper)
config.yml is the standart.
this is what i did:
download spain-latest.osm.pbf and recent_core
mvn package -DskipTests

java -jar -Xmx8g matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar import spain-latest.osm.pbf --vehicle foot
ava -jar -Xmx10g matching-web/target/graphhopper-map-matching-web-1.0-SNAPSHOT.jar match cf.gpx --gps_accuracy 5 --max_visited_nodes 100000
[cf.gpx.zip](https://github.com/graphhopper/map-matching/files/3961488/cf.gpx.zip)

**Comment by karussell** [comment]
Thanks, for this. I can reproduce the problem.
