### ISSUE TITLE
Error while importing pbf

### ISSUE THREAD

**Issue by ugochirico** [graphhopper/map-matching#99]
I checked out the head version of graphhopper-ios and followed the instructions in readme.
I downloaded the pbf from geofabrik.de but when I run import-sample.sh I got this error:

```
666-Mac:graphhopper-ios ugos$ FILE=sud-latest.osm.pbf JAVA_OPTS="-Xmx4096m -Xms1000m -server" ./graphhopper-ios-sample/import-sample.sh
Note: checking out 'origin/master'.
....
## using java 1.8.0_131 (64bit) from 
## using existing osm file graph-data.osm.pbf
## existing jar found tools/target/graphhopper-tools-0.10-SNAPSHOT-jar-with-dependencies.jar
## now import. JAVA_OPTS=-Xmx4096m -Xms1000m -server
2017-07-01 18:31:12,500 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - version 0.10|2017-06-25T19:47:35Z (5,14,4,3,3,2)
2017-07-01 18:31:12,513 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - graph CH|car|RAM_STORE|2D|NoExt|,,,,, details:edges:0(0MB), nodes:0(0MB), name:(0MB), geo:0(0MB), bounds:1.7976931348623157E308,-1.7976931348623157E308,1.7976931348623157E308,-1.7976931348623157E308, CHGraph|fastest|car, shortcuts:0, nodesCH:(0MB)
2017-07-01 18:31:12,597 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - start creating graph from graph-data.osm.pbf
2017-07-01 18:31:12,597 [main] INFO  com.graphhopper.reader.osm.GraphHopperOSM - using CH|car|RAM_STORE|2D|NoExt|,,,,, memory:totalMB:958, usedMB:25
Exception in thread "main" java.lang.RuntimeException: Problem while parsing file
	at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:202)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:146)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:672)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:641)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:619)
	at com.graphhopper.tools.Import.main(Import.java:31)
Caused by: java.lang.IllegalArgumentException: Input file is not of valid type graph-data.osm.pbf
	at com.graphhopper.reader.osm.OSMInputFile.decode(OSMInputFile.java:129)
	at com.graphhopper.reader.osm.OSMInputFile.<init>(OSMInputFile.java:56)
	at com.graphhopper.reader.osm.OSMReader.openOsmInputFile(OSMReader.java:309)
	at com.graphhopper.reader.osm.OSMReader.preProcess(OSMReader.java:163)
	... 5 more
Previous HEAD position was a2d421c4... i18n: updated several languages
Switched to branch 'ios-compat'
Your branch is up-to-date with 'origin/ios-compat
```

**Comment by karussell** [comment]
For graphhopper-ios please use the issue tracker here: https://github.com/graphhopper/graphhopper-ios/issues

**Comment by ugochirico** [comment]
Sorry. I posted in the wrong place
